# Generated by Django 5.1.7 on 2025-03-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
                (
                    "images",
                    models.ImageField(blank=True, null=True, upload_to="blog_images/"),
                ),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="blog_videos/"),
                ),
            ],
        ),
    ]
