# Generated by Django 5.1.7 on 2025-03-20 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("programming", "Programming"),
                            ("stocks", "Stocks"),
                            ("workouts", "Workouts"),
                            ("history", "History"),
                            ("politics", "Politics"),
                        ],
                        max_length=50,
                    ),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
                ("text_content", models.TextField(blank=True, null=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="PoliticsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("programming", "Programming"),
                            ("stocks", "Stocks"),
                            ("workouts", "Workouts"),
                            ("history", "History"),
                            ("politics", "Politics"),
                        ],
                        max_length=50,
                    ),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
                ("text_content", models.TextField(blank=True, null=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="ProgrammingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("programming", "Programming"),
                            ("stocks", "Stocks"),
                            ("workouts", "Workouts"),
                            ("history", "History"),
                            ("politics", "Politics"),
                        ],
                        max_length=50,
                    ),
                ),
                ("repo_link", models.URLField(blank=True, null=True)),
                ("demo_link", models.URLField(blank=True, null=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("programming", "Programming"),
                            ("stocks", "Stocks"),
                            ("workouts", "Workouts"),
                            ("history", "History"),
                            ("politics", "Politics"),
                        ],
                        max_length=50,
                    ),
                ),
                ("external_link", models.URLField()),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="WorkoutItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("programming", "Programming"),
                            ("stocks", "Stocks"),
                            ("workouts", "Workouts"),
                            ("history", "History"),
                            ("politics", "Politics"),
                        ],
                        max_length=50,
                    ),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
                ("text_content", models.TextField(blank=True, null=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="CodeSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("javascript", "JavaScript"),
                            ("jupyter", "Jupyter"),
                        ],
                        max_length=50000,
                    ),
                ),
                ("code", models.TextField()),
                (
                    "programming_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snippets",
                        to="personal_website.programmingitem",
                    ),
                ),
            ],
        ),
    ]
