# Generated by Django 5.1.7 on 2025-03-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockportfolioitem",
            name="external_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
