# Generated by Django 5.1.7 on 2025-03-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "personal_website",
            "0002_historyitem_politicsitem_programmingitem_stockitem_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="codesnippet",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historyitem",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="portfolio_images/"
            ),
        ),
        migrations.AddField(
            model_name="politicsitem",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="portfolio_images/"
            ),
        ),
        migrations.AddField(
            model_name="programmingitem",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="portfolio_images/"
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="portfolio_images/"
            ),
        ),
        migrations.AddField(
            model_name="workoutitem",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="portfolio_images/"
            ),
        ),
    ]
