# Generated by Django 5.1.7 on 2025-03-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_website", "0003_codesnippet_description_historyitem_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historyitem",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="portfolio_videos/"
            ),
        ),
        migrations.AddField(
            model_name="politicsitem",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="portfolio_videos/"
            ),
        ),
        migrations.AddField(
            model_name="programmingitem",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="portfolio_videos/"
            ),
        ),
        migrations.AddField(
            model_name="programmingitem",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="portfolio_videos/"
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workoutitem",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="portfolio_videos/"
            ),
        ),
    ]
